[package]
name = "kiosk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.19"
gloo = "0.6"
wasm-bindgen = "0.2.79"